### ISSUE TITLE
questions / ideas / rejiggering

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi-binary-builds#23]
A few thoughts on `download.ts`.

- should we parameterize `cacheDir`? / the consumer would specify the cache dir / we'd get rid of usage of the `cache_dir` dep and the related possible error throwing
- `download` could accept a third argument, the path at which to install the given bin
- get rid of checking to see if the binary is downloaded at the given path

In Capi, we would then...

- create the download path once
- check to see if exists, and if not, log out that it's downloading
- use the new `download`

Also, might `install` make for a better name, given that––in addition to downloading––it makes the download executable?

Last thing: why do we download to a temp file and then rename it after setting the permissions? / why not `Deno.open`?

**Comment by tjjfvi** [comment]
> should we parameterize `cacheDir`? / the consumer would specify the cache dir / we'd get rid of usage of the `cache_dir` dep and the related possible error throwing

The binaries are rather large and thus should ideally never be downloaded multiple times, so the cache dir should be in a consistent location. We should just make the cache dir determination lazy to avoid throwing immediately in the browser.

> In Capi, we would then...
> - create the download path once
> - check to see if exists, and if not, log out that it's downloading
> - use the new download

I don't see how this is beneficial; it's just moving logic out of cbb into capi. Anyone else consuming our binaries would need to reimplement this logic.

> Also, might `install` make for a better name, given that––in addition to downloading––it makes the download executable?

To me, `install` suggests that it's doing something nontrivial in addition to downloading. Since all it does is download and chmod, it doesn't go into the user's path, etc.

> Last thing: why do we download to a temp file and then rename it after setting the permissions?

That way if the process is killed during the download there isn't a malformed file at the path which will prevent redownloading.

> why not `Deno.open`?

Not sure what you mean here; it is using `Deno.open`

**Comment by harrysolovay** [comment]
> I don't see how this is beneficial

Tools which utilize capi-binary-builds may want to take responsibility for all logging. In the case of Capi, we definitely do (for instance, having a silent/log-level flag in the CLI that disables logging). In the case of `download`, we only want to log if it isn't already downloaded, which we can't easily check without depending on `cache_dir` and re-forming the download path.

> Since all it does is download and chmod, it doesn't go into the user's path, etc

Makes sense.

> That way if the process is killed during the download there isn't a malformed file at the path which will prevent redownloading.

Very, very good point

> Not sure what you mean here; it is using `Deno.open`

Meant opening directly at the final path (which you clarified isn't desirable incase the process is killed).
